/**
 * The 100 communes of Luxembourg (post-2023 mergers). Static on purpose —
 * Apimo exposes no city/commune catalog (city only appears embedded on a
 * listing once it's entered), so this covers the full country regardless
 * of what's currently in Apimo's inventory.
 */
export const luxembourgCommunes = [
  'Beaufort',
  'Bech',
  'Beckerich',
  'Berdorf',
  'Bertrange',
  'Bettembourg',
  'Bettendorf',
  'Betzdorf',
  'Bissen',
  'Biwer',
  'Boulaide',
  'Bourscheid',
  'Bous-Waldbredimus',
  'Clervaux',
  'Colmar-Berg',
  'Consdorf',
  'Contern',
  'Dalheim',
  'Diekirch',
  'Differdange',
  'Dippach',
  'Dudelange',
  'Echternach',
  'Ell',
  'Erpeldange-sur-Sûre',
  'Esch-sur-Alzette',
  'Esch-sur-Sûre',
  'Ettelbruck',
  'Feulen',
  'Fischbach',
  'Flaxweiler',
  'Frisange',
  'Garnich',
  'Goesdorf',
  'Grevenmacher',
  'Groussbus-Wal',
  'Habscht',
  'Heffingen',
  'Helperknapp',
  'Hesperange',
  'Junglinster',
  'Käerjeng',
  'Kayl',
  'Kehlen',
  'Kiischpelt',
  'Koerich',
  'Kopstal',
  'Lac de la Haute-Sûre',
  'Larochette',
  'Lenningen',
  'Leudelange',
  'Lintgen',
  'Lorentzweiler',
  'Luxembourg',
  'Mamer',
  'Manternach',
  'Mersch',
  'Mertert',
  'Mertzig',
  'Mondercange',
  'Mondorf-les-Bains',
  'Niederanven',
  'Nommern',
  'Parc Hosingen',
  'Pétange',
  'Préizerdaul',
  'Putscheid',
  'Rambrouch',
  'Reckange-sur-Mess',
  'Redange-sur-Attert',
  'Reisdorf',
  'Remich',
  'Roeser',
  'Rosport-Mompach',
  'Rumelange',
  'Saeul',
  'Sandweiler',
  'Sanem',
  'Schengen',
  'Schieren',
  'Schifflange',
  'Schuttrange',
  'Stadtbredimus',
  'Steinfort',
  'Steinsel',
  'Strassen',
  'Tandel',
  'Troisvierges',
  'Useldange',
  "Vallée de l'Ernz",
  'Vianden',
  'Vichten',
  'Waldbillig',
  'Walferdange',
  'Weiler-la-Tour',
  'Weiswampach',
  'Wiltz',
  'Wincrange',
  'Winseler',
  'Wormeldange'
] as const;

/**
 * Luxembourg City's 24 official districts (source: vdl.lu). People search
 * by neighborhood ("Gare", "Belair", "Kirchberg"...) far more than by the
 * commune name "Luxembourg" itself — communes alone missed every one of
 * these.
 */
export const luxembourgCityDistricts = [
  'Beggen',
  'Belair',
  'Bonnevoie-Nord/Verlorenkost',
  'Bonnevoie-Sud',
  'Cents',
  'Cessange',
  'Clausen',
  'Dommeldange',
  'Eich',
  'Gare',
  'Gasperich',
  'Grund',
  'Hamm',
  'Hollerich',
  'Kirchberg/Kiem',
  'Limpertsberg',
  'Merl',
  'Mühlenbach',
  'Neudorf/Weimershof',
  'Pfaffenthal',
  'Pulvermühl',
  'Rollingergrund/Belair-Nord',
  'Ville Haute',
  'Weimerskirch'
] as const;

/** Combined, deduplicated, alphabetical — what search/filter UIs should use. */
export const luxembourgLocations = Array.from(
  new Set<string>([...luxembourgCommunes, ...luxembourgCityDistricts])
).sort((a, b) => a.localeCompare(b, 'fr'));
